/* SPDX-License-Identifier: GPL-2.0-or-later */
#include <err.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ls.h"
#include "my_assert.h"

/* Tests the code that looks for video files in the dash cam directory. */

/* Test data definition. “present” should be initialized to false, then turned
 * into true during the assert phase.
 */
struct expected {
  bool present;
  const char filename[28];
};

/* Happy path test */
static void test_sample_directory(void) {
  const int test_case = 1;
  // Arrange
  struct expected expect[] = {
    {false, "20240806193829_005713.TS"},
    {false, "20240821123328_003981.TS"},
    {false, "RO/20240818032421_008259.TS"},
    {false, "short_name.TS"},
  };

  // Act
  struct dirent **list;
  int n = list_to_import("../test/data/directory",
    "../test/data/directory.sqlite", &list);

  // Assert

  // Expected return value: number of files found.
  my_assert(n == sizeof(expect) / sizeof(struct expected));

  for (int i = 0; i < n; ++i) {
    // Only care about .filename.
    for (int j = 0; j < n; ++j)
      if (strcmp(list[i]->d_name, expect[j].filename) == 0)
        expect[j].present = true;
    free(list[i]);
  }

  free(list);

  for (int i = 0; i < n; ++i)
    if (!expect[i].present) {
      fail(
        "Expected file name “%s” at position %d was not present",
        expect[i].filename, i);
      return;
    }
  ok();
}


/* When this is not a directory, it should just return no files. */
static void test_no_directory(void) {
  const int test_case = 2;
  // Act, Assert
  my_assert(0 == list_to_import("", "", NULL));
  ok();
}

/* It also shouldn’t fail when not having a RO directory, generated by the dash
 * cam.
 */
static void test_no_RO(void) {
  const int test_case = 3;
  // Act
  struct dirent **list;
  int n = list_to_import("../test/data/directory_noRO",
    "../test/data/directory.sqlite", &list);

  // Assert
  my_assert(n == 0);
  free(list);
  ok();
}

int main(void) {
  puts("1..3");
  test_sample_directory();
  test_no_directory();
  test_no_RO();
  return 0;
}
